[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmds = ["cd server && npm ci --only=production"]

[phases.build]
cmds = ["echo 'No build step needed for server'"]

[start]
cmd = "cd server && npm start"